### ISSUE TITLE
Create ReadTheDocs Website account for MELODIES-MONET

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-CSL/MELODIES-MONET#10]
@rschwant Can you create the MELODIES-MONET readthedocs website account.  I think that we can add multiple people to the account once it is created.  Once that is done we can setup the link between GitHub and ReadTheDocs to automatically create docs upon a push or pull request.

**Comment by zmoon** [comment]
@rschwant has done this and it is live (at least the develop branch)
