### ISSUE TITLE
Add RAQMS reader to MELODIES MONET

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#107]
Add RAQMS reader to MONETIO. Update driver and ReadTheDocs in MELODIES MONET to use the new RAQMS reader.

**Comment by zmoon** [comment]
xref: https://github.com/NOAA-CSL/MELODIES-MONET/pull/99 https://github.com/noaa-oar-arl/monetio/pull/85

**Comment by mebruckner** [comment]
Am working to finish checking changes as well as update the documentation. I ran into a potential issue regarding plots. Within surfplots for the spatial plots (make_spatial_bias and make_spatial_overlay), the default lat/lon minimum and maximum values for domain_type == all is a CONUS bounding. 
@zmoon how should I proceed? Should this be changed, or for any model is a domain_type of all just Conus and something else be used to push to the else statement in the map generation?

**Comment by zmoon** [comment]
@mebruckner that is a good point, probably this should be updated so that "all" is actually all[^a] and we can have a separate "CONUS" option. We can open a separate issue for this.

I think currently if you just don't set `domain_type` (just delete the line in your config), you should get the behavior I think you are looking for (the `else` branch).

[^a]: Though some of the obs datasets we use are essentially limited to CONUS.

**Comment by mebruckner** [comment]
Thanks- I'd already worked around it in my personal scripts and codebase. It doesn't actually cause any issues in generating plots, I just came across it again while ensuring RAQMS is included in the plot setups. There just might be some user confusion if the obs and model sets include points outside the spatial plotting domain which are then included in the other plots and statistics (which does happen with the current all behavior).

Documentation for the RAQMS addition will be complete before the weekend, and I will push the new commits for approval.

**Comment by zmoon** [comment]
> It doesn't actually cause any issues in generating plots,

Except that if there are points outside the CONUS domain you wouldn't see them, yes?

But your other point about the averages and stats seems the more important, I will open issue.

**Comment by mebruckner** [comment]
Yes, any points outside the CONUS domain just wouldn't be visible in the spatial plots when the user gives domain_type == all under the current construction due to the choice of minimum and maximum lat/lons for the plot extent.

**Comment by mebruckner** [comment]
In running my  test notebook I ran into an issue with the aeronet pairing that arises from the aod field in RAQMS not having a z-dimension. I had bypassed this issue by adding a try/execpt that would bypass the z issue for 2d model fields. This could be a special case sort of situation, so I don't know the to handle it.

**Comment by zmoon** [comment]
hmm, we could add a surface-only option to the reader like the WRF-Chem one has?

**Comment by zmoon** [comment]
@mebruckner I added a `surf_only` option in a branch here if you want to try it https://github.com/zmoon/monetio/tree/raqms with something like
```yaml
model:
  RAQMS:
    mod_type: raqms
    mod_kwargs:
      surf_only: true
```

**Comment by mebruckner** [comment]
Zach, thanks for adding this option. It does work.

**Comment by rschwant** [comment]
This is now in the develop branch of MELODIES MONET and complete: https://github.com/NOAA-CSL/MELODIES-MONET/pull/147. I'm closing this issue.
