### ISSUE TITLE
Begin editing the .rst files for MELODIES-MONET

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-CSL/MELODIES-MONET#11]
@rrbuchholz I created a branch that has the essence of the documentation that I used for MONETIO.  This should help with creating the file structure that we need for the documentation.  If you want to begin editing the rst files with what you have created in the google doc you can.  Let me know if you have questions and I can point you in the right direction.

**Comment by zmoon** [comment]
I think the docs have developed enough that we could feel good closing this issue.

**Comment by rschwant** [comment]
Agreed good work everyone. Now we are entering more maintenance mode.
