### ISSUE TITLE
Add MELODIES-MONET example on JupyterHub (or similar)

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#120]
Let's add MELODIES-MONET example on JupyterHub (or another) for conferences, link to the docs. This way people can provide something similar for conferences. @dwfncar  and @mebruckner were working on this for the Earth Cube Conference and ran into memory problems. Once these are resolved, let's get an example working that people can point to.

**Comment by zmoon** [comment]
The idealized example should run on Binder, I could make a link for that.

**Comment by dwfncar** [comment]
JupyterHub memory limits prevented a full example for EarthCube summer '22.
