### ISSUE TITLE
Failed to run MELODIES-MONET on Hera

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-CSL/MELODIES-MONET#134]
Hi, I failed to run MELODIES-MONET when I verified  the UFS-AQM results

Below is the error message
    raise ValueError(msg)
ValueError: unable to decode time units 'hours since 2019-08-801 12:00:00' with "calendar 'JULIAN'". Try opening your dataset with decode_times=False or installing cftime if it is not installed.

1) The control yam file
/scratch2/NCEPDEV/naqfc/Jianping.Huang/MONET/main/ufsaqm_analysis/v7.0.c14/control_ufsaqm_example_submit_job.yaml

2) run log file
/scratch2/NCEPDEV/naqfc/Jianping.Huang/MONET/main/ufsaqm_analysis/v7.0.c14/slurm-37155217.out

Any suggestion ?

Thanks,

Jianping

**Comment by zmoon** [comment]
Hi @JianpingHuang-NOAA . Assuming your error message is correct, the time unit in the netCDF file needs to be fixed. 'hours since 2019-08-**801** 12:00:00' probably should be 'hours since 2019-08-**01** 12:00:00'

**Comment by rschwant** [comment]
@JianpingHuang-NOAA, did this work? Can I close this issue?

**Comment by JianpingHuang-NOAA** [comment]
Yes, it works. Please close it.

Jianping

**Comment by rschwant** [comment]
Great, closing this issue because it has been resolved.
