### ISSUE TITLE
Spatial bias plot error with mpl 3.6

### ISSUE THREAD

**Issue by zmoon** [NOAA-CSL/MELODIES-MONET#135]
Got error message: `unhashable type: 'ListedColormap'` in spatial bias plot

Abbreviated traceback:

`monet.plots.sp_scatter_bias(..., cmap=new_color_map(), ...)` passes a custom `ListedColormap`.
In monet, this is passed through to pandas `df.plot.scatter`

Based on the message below, it seems pandas is expecting a cmap name if mpl >= 3.6?

```
│ /scratch/zmoon/mambaforge/envs/mm/lib/python3.9/site-packages/pandas/plottin │
│ g/_matplotlib/core.py:1225 in _make_plot                                     │
│                                                                              │
│   1222 │   │                                                                 │
│   1223 │   │   if self.colormap is not None:                                 │
│   1224 │   │   │   if mpl_ge_3_6_0():                                        │
│ > 1225 │   │   │   │   cmap = mpl.colormaps[self.colormap]                   │
│   1226 │   │   │   else:                                                     │
│   1227 │   │   │   │   cmap = self.plt.cm.get_cmap(self.colormap)            │
│   1228 │   │   else:
```

**Comment by zmoon** [comment]
For anyone who needs a quick fix, `conda install 'matplotlib-base <3.6'`. But I will work on resolving this for mpl 3.6.

**Comment by jianheACM** [comment]
@zmoon @rschwant I had the same issue after updating the pkg.

Below is my quick fix:
In function new_color_map
...
    newcmap = ListedColormap(newcolors, name='OrangeBlue')
    mpl.colormaps.register(newcmap)

    return newcmap

In spatial bias plot:
...
    newcmap = 'OrangeBlue'
    try:
        mpl.colormaps[newcmap]
    except KeyError:
        new_color_map()
...

This will work for matplotlib >=3.6

**Comment by zmoon** [comment]
@jianheACM the bug in pandas was [fixed in v1.5.2](https://pandas.pydata.org/docs/whatsnew/v1.5.2.html#fixed-regressions). What is your pandas version?

**Comment by zmoon** [comment]
Registering and using the string name seems like a good workaround though, maybe we should add this to MM anyway.

**Comment by jianheACM** [comment]
It's v1.5.1. But it's good to know it is fixed in v1.5.2. 
I feel like we will have some similar issues in the future if we update pkg version.

**Comment by rschwant** [comment]
@jianheACM and @zmoon if you feel like registering the colormap like Jian did above will lead to less package versioning incompatibilities, I'm fine with updating this like Jian suggests.

**Comment by rschwant** [comment]
A better method for this has been merged to develop, to avoid future problems. Since this doesn't cause problems currently I am closing it.
https://github.com/NOAA-CSL/MELODIES-MONET/pull/154
