### ISSUE TITLE
Add filter option for AQS data specifically, but make it general

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#146]
We need a general filter option. First we may want to use this for the AQS data to filter based on the measurement_scale to remove micro sites. But I'm sure there are other applications for this too, so we should make it general. This may be relevant for the aircraft evaluation too.

Maybe something like this in the yaml file:
- `filter_opt`: This could be the expr like '==' below
- `filter_dict`: This could be a dictionary where the keys are columns of the dataframe and the values are a list to accomodate multiple values being selected at once.

We probably just want to add into the code [a query option](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html) like we have done with the domains. 

https://github.com/NOAA-CSL/MELODIES-MONET/blob/0d2ca12e5ec46f4f595ce3e18e1acd680a5534c0/melodies_monet/driver.py#L726-L728

This is just a start it probably would take a bit more time to think of a good format for this, but I don't think it would be too hard.

**Comment by rschwant** [comment]
-Make sure keep the relevant site information from the observations.
-Filter on the number of observations or as a separate yaml structure.
-Two options: one prior to pairing and one during the analysis

**Comment by mebruckner** [comment]
In order to do the filtering of Aeronet data I did for Brad Pierce's AGU22 poster, I add the following to my work flow between opening the observations and running the pairing.

```
# restriction of observations to analysis window specfied in yaml
an.obs['aeronet'].obj = an.obs['aeronet'].obj.sel(time=slice(an.start_time,an.end_time))

# removal of data for sites from the analysis scheme where there are fewer than x% of days reporting data
site_groups = an.obs['aeronet'].obj.groupby('siteid')#,'time'.dt.day)
for label,group in site_groups:
    #pull site, re-group to daily means
    tst = an.obs['aeronet'].obj['aod_550nm'][site_groups.groups[label]].groupby('time.dayofyear').mean().squeeze()
    if len(tst[~np.isnan(tst)]) < .5*len(tst): # filter to if <50% of days at site have data
        an.obs['aeronet'].obj['aod_550nm'][site_groups.groups[label]] = np.nan
        print('removed {}'.format(label))
        print('nobs:',len(tst[~np.isnan(tst)]))
```

**Comment by rschwant** [comment]
Colin updated to add filtering options. So this is complete.
