### ISSUE TITLE
Update projections

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#21]
Right now the projections are hardwired in the surface plot data to use the native projection for each model. If you input a new model into the system the code will break. 

1) I need to change this so that instead of breaking it just uses a default.  
2) I have since decided it's more useful to inter-compare model results when they are on the same projection. So I want to add an option in the namelist for the user to define a projection to use for each of the plots. If nothing is defined, it will use a default for all plots
3) I want to keep an option for plotting on the native model projection as well, so you can select this option in the namelist too. And I want the projection for each model to be defined in that attributes in the i/o read script.

**Comment by rschwant** [comment]
This has been fixed by #164 #168 and #169. There are now several options available that are explained in the docs in https://melodies-monet.readthedocs.io/en/latest/appendix/yaml.html

**Comment by zmoon** [comment]
Current: https://melodies-monet.readthedocs.io/en/develop/appendix/yaml.html#models
