### ISSUE TITLE
potential issue with pairing observation, missing hours pair

### ISSUE THREAD

**Issue by btang1** [NOAA-CSL/MELODIES-MONET#238]
when I am running and develop MONET code. I print out the pairdf_all and pairdf and find there is a potential paring issue.

so I have observation from AirNow (08/01 0am to 08/31 23pm). and 2 model runs from CMAQ AQM (08/15 1am to 08/31 23pm).

if print out 'pairdf_all' it start at 08/15 1am. and print out 'pairdf' for 1st start at '08/15 13pm' 
and 'pairdf' for 2nd model  start at '08/15 1am'.  I am sure both model start save time at (08/15 1am)

further debugging suggest that there are missing observation between '08/15 2am - 11am for AirNow'.

But why MONET drop paired observation for 1st model, but keep 1am observation for the 2nd model?

if request, I can provide more details in a slide. Thanks!

**Comment by zmoon** [comment]
Did you check them before the NaN dropping?
https://github.com/NOAA-CSL/MELODIES-MONET/blob/067ef1e8df38d9239fb7411c20ff856be1de6203/melodies_monet/driver.py#L1201-L1206
(and before any selection by time or domain)

Feel free to provide the slide for more info.

**Comment by btang1** [comment]
thanks @zmoon I checked the pairdf_all has all time and domain with nan values, and after dropping nan 'pairdf' has no observation at 1am. even though it should.

I will send the slide later this week.

**Comment by zmoon** [comment]
Also if you share your control file location I could investigate as well.

**Comment by btang1** [comment]
Control file in folder: /home/btang6/python

And I use ‘job_script_XnodeXcores.sh’ which should read 'Compare_3cmaq_airnow_AGU2023.yaml’ when I try to read 3 models.

Change starttime to 08/15/2024 13pm solve the problem, but if you set start time as 08/15/2023 1am, you will see different model have different pairdf start time if print out. While pairdf_all remain the same.



On Jan 24, 2024, at 12:20 AM, Zachary Moon ***@***.***> wrote:



Also if you share your control file location I could investigate as well.

**Comment by zmoon** [comment]
Thanks for sharing that. Which variable (O3, PM2.5, ...) is this for? Is it the same for other variables?

**Comment by btang1** [comment]
I only check pm2.5.



Sent from my iPhone

On Jan 30, 2024, at 2:25 PM, Zachary Moon ***@***.***> wrote:

﻿

Thanks for sharing that. Which variable (O3, PM2.5, ...) is this for? Is it the same for other variables?

**Comment by btang1** [comment]
I checked all AQM runs.
if model output start at 13pm, 'time' variable start at 12pm, 'time_iso' is 13pm. NO PROBLEM!
if model output start at 1am, 'time' variable start at 12pm, 'time_iso' is 1 meaning 13pm. That is the problem.
This happened in all model runs output at 1am. and could be some thing happen when output the model results. not post-processing step.

**Comment by bbakernoaa** [comment]
@btang1 @zmoon is this resolved now?

**Comment by btang1** [comment]
@zmoon @bbakernoaa I have a branch in my home GitHub that can print out different model numbers, when this problem happen. just give a waring to user that the size do not match. 
my branch is here:https://github.com/btang1/MELODIES-MONET/tree/PairOBS 
and the result is here: https://docs.google.com/presentation/d/15GxUcM139Dns4K4VPmUexPdMMcdwJe9l/edit?usp=share_link&ouid=117233739375959098251&rtpof=true&sd=true

**Comment by zmoon** [comment]
@btang1 I think we can close this since we have #245
