### ISSUE TITLE
MELODIES-MONET plotting not working with matplotlib 3.9.1

### ISSUE THREAD

**Issue by blychs** [NOAA-CSL/MELODIES-MONET#262]
Me and @dwfncar were just trying to run  docs/examples/airnow_wrfchem.ipynb in a fresh conda environment, following the instructions in the docs (that is, with pandas v1). This was tested on the develop branch version on this repo.
During an.plotting(), we got the following error:
![image](https://github.com/user-attachments/assets/27af9927-920a-4451-b70b-f87423ce26fa)

There is an easy fix: restricting the matplotlib version to 3.8 or lower. We have tried doing just that change

If this is the case, we need to update the docs to include matplotlib=3.8 instead of just matplotlib in the conda install command until we find out a fix.

The readthedocs should state

$ conda install -y -c conda-forge pyyaml pandas=1 monet monetio netcdf4 wrf-python typer rich pooch jupyterlab

**Comment by zmoon** [comment]
I think #259 addressed this, could close.
