### ISSUE TITLE
New incompatibility: numpy.NaN is deprecated

### ISSUE THREAD

**Issue by blychs** [NOAA-CSL/MELODIES-MONET#263]
Hi all,
This might be already enforced by matplotlib<3.9 (I haven't tested that). However, the new numpy 2.0.0 (released a month ago), that was just added to conda-forge, deprecates np.NaN and replaces is by np.nan.
I am still trying to understand which package is really requiring it, I got the error while trying to compile locally the docs in my personal computer (I had it in a cluster before, since I can't compile wrf-python in my local computer due to it being apple silicon).

I will edit this issue when I have more info.

**Comment by zmoon** [comment]
@blychs [looks like](https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals) it was *removed* for NumPy v2. It should be safe to update all code to use `np.nan`, which works in NumPy v1 as well.

**Comment by blychs** [comment]
That's right. However, I just can't find any of our code using it, but building the docs fails with that version of numpy.

**Comment by zmoon** [comment]
MONET has a few (and MONETIO a lot), that could be the issue. Does the traceback show any info about where the error occurred?

**Comment by blychs** [comment]
When building the docs, I only get that it cannot import driver.py because it cannot find numpy.NaN -which makes sense.
It is likely as you say.
I will finish testing this, hopefully next week at the latest.

**Comment by blychs** [comment]
Can this be closed @zmoon @rschwant ? I believe that this was fixed at the MONETIO level.

**Comment by zmoon** [comment]
Fine with me. Though, do you want to add some info about this to #266 ?
