### ISSUE TITLE
Add FAQ for common errors to ReadTheDocs

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#264]

**Comment by blychs** [comment]
@rschwant Do you think that this is done with Troubleshooting? Or should we add a separate section?

**Comment by rschwant** [comment]
Yes, this is solved with Troubleshooting. Thanks, you can close it. Or if you do not have permissions. I will do it.

**Comment by blychs** [comment]
I only have permissions to close issues that I opened myself

**Comment by rschwant** [comment]
Good to know, this is complete with this pull request: https://github.com/NOAA-CSL/MELODIES-MONET/pull/266
