### ISSUE TITLE
Satellite time series (and probably other plots) has been broken by aircraft checks in the driver.

### ISSUE THREAD

**Issue by blychs** [NOAA-CSL/MELODIES-MONET#279]
The problem is still the same as in issue #278: a check for pairdf.columns. In the satdata, we have xr.Datasets and not pd.DataFrames.
The code states
```
                            elif filter_criteria is None:
                                if 'altitude' in pairdf.columns:
                                    vmin_y2 = pairdf['altitude'].min()
                                    vmax_y2 = pairdf['altitude'].max()
                                else:
                                    vmin_y2 = vmax_y2 = None

```
This means that when filter_criteria is None, the timeseries plots break, since pairdf.columns does not exist. @dwfncar or @mlirenzhenmayi maybe can confirm this?
I have a simple workaround for TEMPO, which is using the satplot tool that I mentioned in the meeting and/or avoiding that check for satellite, but I remember that @rschwant wanted to avoid adding too many extra checks in the driver.
Cheers
Pablo

**Comment by rschwant** [comment]
This is fixed now
