### ISSUE TITLE
Is it possible that the labels in the CSI tool are wrong?

### ISSUE THREAD

**Issue by blychs** [NOAA-CSL/MELODIES-MONET#287]
In the wrf-chem example, the first label says "Airnow" and the second says "WRF-Chem". To me, this is very confusing, since:
a) There are two WRF-Chem mechanisms tested there
b) the "CSI" of Airnow doesn't make any sense: the values are compared against Airnow.
I believe, also seeing the examples that @btang1 sent to me, that we would expect the labels to be RACM_ESRL and RACM_ESRL_VCP.
Is that correct, @btang1?

Cheers
Pablo

**Comment by btang1** [comment]
yes. it is currently wrong in example file. those 2 should be names of 2 model, not include observations.
see my yaml file example attached.

![Screenshot 2024-10-07 at 1 24 52 PM](https://github.com/user-attachments/assets/d8a587c7-c8de-4dca-bb86-28892b6bb9ec)

**Comment by btang1** [comment]
@blychs

**Comment by blychs** [comment]
Thanks! I believe Becky is addressing this in #285 .
Cheers
Pablo

**Comment by rschwant** [comment]
This is fixed now!
