### ISSUE TITLE
Incorporate aircraft observations pairing into driver

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#30]
I started setting up the pairing for aircraft observations. All of this is in a jupyter notebook in MELODIES-MONET/melodies_monet/examples/jupyter_notebooks/Monet-analysis-example-plots-cmaq-vert2.ipynb. We need to convert this pairing into the driver. 

Then once this is done. Jian, Siyuan, and I can begin to incorporate our python matplotlib plotting routines in as well. I will work on this likely in December. If others want to help move this forward faster let me know.

**Comment by quaz115** [comment]
Added Vertical Profile plot(s) (specific to FIREX as a first example): [https://github.com/NOAA-CSL/MELODIES-MONET/pull/181/files]

**Comment by rschwant** [comment]
Pairing has successfully been incorporated into the driver in the develop_aircraft branch for
mobile and ground
https://github.com/NOAA-CSL/MELODIES-MONET/pull/185

and aircraft
https://github.com/NOAA-CSL/MELODIES-MONET/pull/101

So I'm closing this issue as basic pairing has been incorporated.
