### ISSUE TITLE
Bug in develop_tempo if only 1 swath is chosen

### ISSUE THREAD

**Issue by noribeth-m** [NOAA-CSL/MELODIES-MONET#311]
When only 1 swath is chosen, the time dimension is not created and fails at selecting the time. @blychs

**Comment by blychs** [comment]
Thanks, Nori! It was an identation error (i. e, the tool was only gridding back to modgrid if there was more than one scan).
Fixed in develop_tempo, commit c7365269701809938ed99a8d1af5bd2843dd410c
Please pull that latest commit.
Closing this issue.
