### ISSUE TITLE
Avoid re-starting the kernel

### ISSUE THREAD

**Issue by rrbuchholz** [NOAA-CSL/MELODIES-MONET#33]
If changing something in the driver or a program called by the driver, how to we avoid having to re-start the kernel. That is, how can we force a re-import?

**Comment by zmoon** [comment]
I think IPython auto-reload is the best advice we can offer.

However, I will add that I have gotten the best auto-reload experience with Spyder, as it is automatic and seems to work a bit better than just IPython. But Spyder may be inconvenient/slow to use on Cheyenne/whatnot.
