### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rschwant** [NOAA-CSL/MELODIES-MONET#41]
Let's discuss licenses in Thursday's meeting. We can use a similar license to that in MONET and MONETIO or does NCAR have a standard license? I basically just want something that says something similar to this: https://github.com/noaa-oar-arl/monetio/blob/master/LICENSE

**Comment by zmoon** [comment]
With #60 merged we might be able to close this

**Comment by rschwant** [comment]
This is done.
