### ISSUE TITLE
Disable progress bars

### ISSUE THREAD

**Issue by zmoon** [NOAA-CSL/MELODIES-MONET#95]
Would be nice to provide an option to disable Dask progress bars (they make log files from a non-interactive run hard to read). [Seems like](https://stackoverflow.com/a/43121416) it is possible to unregister all that may have been registered (e.g. in monetio). Just need to implement a MM config option.

**Comment by zmoon** [comment]
This is resolved in develop (#95).

**Comment by rschwant** [comment]
And is now in main.
